import colors from "./colors";

export default {
  loadData: [
    {
      cost: "$233",
      type: "Pick Up",
      weight: "+42k lbs",
      total: "197 mi total",
      from: "Los Angeles US",
      fromDate: "Jan 28, 14:30 CST",
      to: "San Francisco Us",
      toDate: "Jan 28, 14:30 CST",
    },
    {
      cost: "$233",
      type: "Pick Up",
      weight: "+42k lbs",
      total: "197 mi total",
      from: "Los Angeles US",
      fromDate: "Jan 28, 14:30 CST",
      to: "San Francisco Us",
      toDate: "Jan 28, 14:30 CST",
    },
    {
      cost: "$233",
      type: "Pick Up",
      weight: "+42k lbs",
      total: "197 mi total",
      from: "Los Angeles US",
      fromDate: "Jan 28, 14:30 CST",
      to: "San Francisco Us",
      toDate: "Jan 28, 14:30 CST",
    },
    {
      cost: "$233",
      type: "Pick Up",
      weight: "+42k lbs",
      total: "197 mi total",
      from: "Los Angeles US",
      fromDate: "Jan 28, 14:30 CST",
      to: "San Francisco Us",
      toDate: "Jan 28, 14:30 CST",
    },
  ],
  drivers: [
    {
      status: "Empty",
      color: colors.green,
      name: "Fay B",
      currentLocation: "Houston Tx",
      bookedLoads: 3,
    },
    {
      status: "Offline",
      color: colors.lightGray2,
      name: "Fay B",
      currentLocation: "Houston Tx",
      bookedLoads: 4,
    },
    {
      status: "Empty",
      color: colors.green,
      name: "Fay B",
      currentLocation: "Houston Tx",
      bookedLoads: 1,
    },
    {
      status: "Loaded",
      color: colors.orange,
      name: "Fay B",
      currentLocation: "Houston Tx",
      bookedLoads: 3,
    },
    {
      status: "Loaded",
      color: colors.orange,
      name: "Fay B",
      currentLocation: "Houston Tx",
      bookedLoads: 2,
    },
    {
      status: "Empty",
      color: colors.green,
      name: "Fay B",
      currentLocation: "Houston Tx",
      bookedLoads: 5,
    },
  ],
};
