export default {
  addDriver: "Add Driver",
  addMember: "Add Member",
  bookHome: "Book",
  driverHome: "Driver",
  favorite: "Favorite",
  loadHome: "Load",
  singleLoadDetails: "Single Load Details",
  accountHome: "Account",
  home: "Home",
  contractTerms: "Contract Terms",
  description: "description",
  dotNumber: "Dot Number",
  imageCarousel: "Image Carousel",
  landingPage: "Landing Page",
  lastAuth: "Last Auth",
  loginLanding: "Login Landing",
  login: "Login",
  notification: "Notification",
  otp: "Otp",
  payment: "Payment",
  paymentSecond: "Payment Second",
  signUp: "Sign Up",
  trailerType: "Trailer Type",
  reviewDetails: "Review Details",
};
