export default {
  addDriver: "Add Driver",
  addMember: "Add Member",
  bookHome: "Book",
  driverHome: "Driver",
  loadHome: "Load",
  accountHome: "Account",
  home: "Home",
  contractTerms: "Contract Terms",
  description: "description",
  dotNumber: "Dot Number",
  imageCarousel: "Image Carousel",
  landingPage: "Landing Page",
  lastAuth: "Last Auth",
  loginLanding: "Login Landing",
  login: "Login",
  otp: "Otp",
  signUp: "Sign Up",
  trailerType: "Trailer Type",
};
